- hosts: all
  tasks:
    - name: Create destination for logs
      file:
        path: "{{ zuul.project.src_dir }}/log"
        state: directory
        mode: 0755
    - name: 'crashdump'
      args:
        executable: /bin/bash
      shell: |
        set -o pipefail
        for model in $(juju models | grep zaza- | awk '{gsub(/\*?/,""); print $1}'); do
          juju-crashdump \
            -o "{{ zuul.project.src_dir }}/log" \
            -m $model \
            --as-root \
            /etc/apache2 \
            /etc/haproxy \
            /etc/openvswitch \
            /etc/ovn \
            /var/lib/openvswitch \
            /var/lib/ovn \
            /var/snap/simplestreams/common
        done
      when: not zuul_success | bool
    - name: juju status
      args:
        executable: /bin/bash
      shell: |
        set -o pipefail
        for model in $(juju models | grep zaza- | awk '{gsub(/\*?/,""); print $1}'); do
          juju status -m $model > {{ zuul.project.src_dir }}/log/juju-status.$model.txt
          juju status -m $model --format=yaml > {{ zuul.project.src_dir }}/log/juju-status.$model.yaml
        done
    - name: fetch juju logs
      synchronize:
        dest: "{{ zuul.executor.log_root }}"
        mode: pull
        src: "{{ zuul.project.src_dir }}/log"
        verify_host: true
        owner: no
        group: no
    - name: 'force remove Juju machines'
      args:
        executable: /bin/bash
      shell: |
        set -o pipefail
        for model in $(juju models | grep zaza- | awk '{gsub(/\*?/,""); print $1}'); do
          juju remove-machine --force $(seq 0 100)
        done
      failed_when: false
    - name: 'destroy controller'
      shell: >
        timeout 240 juju destroy-controller --destroy-all-models --destroy-storage -y {{ serverstack_cloud.region_name }}-{{ serverstack_cloud.region_name }}
      failed_when: false
    - name: 'kill controller'
      shell: >
        juju kill-controller -t 120s -y {{ serverstack_cloud.region_name }}-{{ serverstack_cloud.region_name }}
      failed_when: false
