# - hosts: localhost
#   tasks:
#   - name: Include Zuul manifest role
#     include_role:
#       name: generate-zuul-manifest
#   - name: Include customized upload logs role
#     no_log: true
#     include_role:
#       name: upload-swift
#     vars:
#       zuul_log_path_shard_build: true
#       # zuul_log_cloud_config: '{{ serverstack_cloud }}'
#       zuul_log_cloud_config: '{{ artifact_cloud }}'
#       # zuul_log_partition: true
#       # 15552000 is 30 days * 6, or ~ 6 months
#       zuul_log_delete_after: 15552000
#       # Unique log prefix to avoid container name collisions when ceph is
#       # used.
#       # zuul_log_container: zuul_logs
#       zuul_log_container: uosci-artifacts

- hosts: localhost
  gather_facts: False
  roles:
    - generate-zuul-manifest
    - role: upload-logs
      zuul_log_url: "http://localhost:8000"

# - hosts: localhost
#   gather_facts: False
#   roles:
#     - generate-zuul-manifest
#     - role: upload-logs
#       zuul_log_url: "http://10.85.132.230:8080"
