zookeeper-servers:
  - host: zookeeper-0.zookeeper-headless.zuul.svc.cluster.local
    port: 2281
  - host: zookeeper-1.zookeeper-headless.zuul.svc.cluster.local
    port: 2281
  - host: zookeeper-2.zookeeper-headless.zuul.svc.cluster.local
    port: 2281
zookeeper-tls:
  ca: /tls/client/ca.crt
  cert: /tls/client/tls.crt
  key: /tls/client/tls.key
providers:
- name: prodstack6 # this is a nodepool identifier for this cloud provider (cloud+region combo)
  region-name: prodstack6  # this needs to match the region name in clouds.yaml but is only needed if there is more than one region
  cloud: prodstack6  # This needs to match the name in clouds.yaml
  boot-timeout: 600  # 10m
  cloud-images:
    - name: noble
      image-name: zosci/ubuntu-noble-24.04-amd64-server-20241119-disk1.img
      username: ubuntu
      python-path: /usr/bin/python3
    - name: jammy
      image-name: zosci/ubuntu-jammy-22.04-amd64-server-20241206-disk1.img
      username: ubuntu
      python-path: /usr/bin/python3
    - name: focal
      image-name: zosci/ubuntu-focal-20.04-amd64-server-20241112-disk1.img
      username: ubuntu
      python-path: /usr/bin/python3
    - name: bionic
      image-name: zosci/ubuntu-bionic-18.04-amd64-server-20230607-disk1.img
      username: ubuntu
      python-path: /usr/bin/python3
    - name: xenial
      image-name: zosci-ubuntu-xenial-daily-amd64-server-20211001-disk1.img
      username: ubuntu
      python-path: /usr/bin/python3
  pools:
    - name: main
      max-servers: 3
      auto-floating-ip: false
      networks:
        - net_stg-openstack-zosci
      security-groups:
        - zosci-sec-group
      labels:
        - name: jammy-medium
          flavor-name: 'staging-cpu4-ram8-disk50'
          cloud-image: jammy
          key-name: nodepool
        - name: focal-medium
          flavor-name: 'staging-cpu4-ram8-disk50'
          cloud-image: focal
          key-name: nodepool
        - name: bionic-medium
          flavor-name: 'staging-cpu4-ram8-disk50'
          cloud-image: bionic
          key-name: nodepool

labels:
  - name: jammy-medium
    min-ready: 1
  - name: focal-medium # defines label that will be used in jobs
    min-ready: 1
  - name: bionic-medium # defines label that will be used in jobs
  - name: xenial-medium
  - name: jammy-brown
  - name: focal-brown
  - name: bionic-brown
